export {
  createAuthIdentityFromSession,
  createPasswordHash,
  createSession,
  createAuthRepository,
  issueSessionTokens,
  mapExternalIdentityToUser,
  normalizeProviderConfig,
  requirePermission,
  resolveAccessDecision,
  resolveRequestAuthIdentity,
  validateLocalPassword,
  validateProviderInput,
  verifySessionToken,
  type AccessDecision,
  type AuthIdentity,
  type AuthenticationMethod,
  type AuthProviderConfig,
  type AuthProviderRecord,
  type AuthProviderSummary,
  type AuthProviderType,
  type AuthSession,
  type AuthSessionRecord,
  type AuthTransactionRecord,
  type AuthUserProviderMapping,
  type AuthUserRecord,
  type FileBackedAuthRepository,
  type LdapAuthConfig,
  type LocalAuthConfig,
  type OidcAuthConfig,
  type SamlAuthConfig,
  type SessionTokenPair
} from "../../auth-core/dist/index.js";
